# Form implementation generated from reading ui file 'ui_files/edit_item_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_edit_item_dialog(object):
    def setupUi(self, edit_item_dialog):
        edit_item_dialog.setObjectName("edit_item_dialog")
        edit_item_dialog.resize(803, 660)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(edit_item_dialog.sizePolicy().hasHeightForWidth())
        edit_item_dialog.setSizePolicy(sizePolicy)
        edit_item_dialog.setMinimumSize(QtCore.QSize(350, 0))
        edit_item_dialog.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.verticalLayout = QtWidgets.QVBoxLayout(edit_item_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.skuInput = QtWidgets.QLineEdit(parent=edit_item_dialog)
        self.skuInput.setObjectName("skuInput")
        self.gridLayout.addWidget(self.skuInput, 5, 0, 1, 1)
        self.skuLabel = QtWidgets.QLabel(parent=edit_item_dialog)
        self.skuLabel.setObjectName("skuLabel")
        self.gridLayout.addWidget(self.skuLabel, 3, 0, 1, 1)
        self.categoryLabel = QtWidgets.QLabel(parent=edit_item_dialog)
        self.categoryLabel.setObjectName("categoryLabel")
        self.gridLayout.addWidget(self.categoryLabel, 0, 2, 1, 1)
        self.categoryInput = QtWidgets.QLineEdit(parent=edit_item_dialog)
        self.categoryInput.setObjectName("categoryInput")
        self.gridLayout.addWidget(self.categoryInput, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.specificationLabel = QtWidgets.QLabel(parent=edit_item_dialog)
        self.specificationLabel.setObjectName("specificationLabel")
        self.gridLayout.addWidget(self.specificationLabel, 7, 0, 1, 1)
        self.nameInput = QtWidgets.QLineEdit(parent=edit_item_dialog)
        self.nameInput.setObjectName("nameInput")
        self.gridLayout.addWidget(self.nameInput, 1, 0, 1, 1)
        self.nameLabel = QtWidgets.QLabel(parent=edit_item_dialog)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout.addWidget(self.nameLabel, 0, 0, 1, 1)
        self.quantitySpinBox = QtWidgets.QSpinBox(parent=edit_item_dialog)
        self.quantitySpinBox.setObjectName("quantitySpinBox")
        self.gridLayout.addWidget(self.quantitySpinBox, 5, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.quantityLabel = QtWidgets.QLabel(parent=edit_item_dialog)
        self.quantityLabel.setObjectName("quantityLabel")
        self.gridLayout.addWidget(self.quantityLabel, 3, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.gridLayout.addItem(spacerItem2, 6, 0, 1, 1)
        self.specificationInput = QtWidgets.QPlainTextEdit(parent=edit_item_dialog)
        self.specificationInput.setObjectName("specificationInput")
        self.gridLayout.addWidget(self.specificationInput, 8, 0, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=edit_item_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Apply|QtWidgets.QDialogButtonBox.StandardButton.Discard|QtWidgets.QDialogButtonBox.StandardButton.Reset|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(edit_item_dialog)
        self.buttonBox.accepted.connect(edit_item_dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(edit_item_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(edit_item_dialog)

    def retranslateUi(self, edit_item_dialog):
        _translate = QtCore.QCoreApplication.translate
        edit_item_dialog.setWindowTitle(_translate("edit_item_dialog", "Dialog"))
        self.skuLabel.setText(_translate("edit_item_dialog", "SKU"))
        self.categoryLabel.setText(_translate("edit_item_dialog", "Category"))
        self.specificationLabel.setText(_translate("edit_item_dialog", "Specification"))
        self.nameLabel.setText(_translate("edit_item_dialog", "Product name"))
        self.quantityLabel.setText(_translate("edit_item_dialog", "Quantity"))
