# Form implementation generated from reading ui file 'ui_files/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.search_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.search_input.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.search_input.setText("")
        self.search_input.setObjectName("search_input")
        self.gridLayout.addWidget(self.search_input, 0, 1, 1, 1)
        self.tableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView.setEnabled(True)
        palette = QtGui.QPalette()
        self.tableView.setPalette(palette)
        self.tableView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.tableView.setMouseTracking(False)
        self.tableView.setTabletTracking(False)
        self.tableView.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tableView.setStyleSheet("")
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 3, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 19))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_export_as = QtGui.QAction(parent=MainWindow)
        self.action_export_as.setObjectName("action_export_as")
        self.action_import = QtGui.QAction(parent=MainWindow)
        self.action_import.setObjectName("action_import")
        self.action_quit = QtGui.QAction(parent=MainWindow)
        self.action_quit.setObjectName("action_quit")
        self.menuFile.addAction(self.action_export_as)
        self.menuFile.addAction(self.action_import)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_quit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        MainWindow.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.search_input.setPlaceholderText(_translate("MainWindow", "Enter search terms..."))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.action_export_as.setText(_translate("MainWindow", "Export as"))
        self.action_import.setText(_translate("MainWindow", "Import"))
        self.action_quit.setText(_translate("MainWindow", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
